
package ProjectGUI;

/**
 *
 * @author Andrew
 */
public class ImportDataForm extends javax.swing.JFrame {

    /**
     * Creates new form ImportDataForm
     */
    public ImportDataForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        passageTab = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        passageTextArea = new javax.swing.JTextArea();
        passageSaveButton = new javax.swing.JButton();
        passageQuestionsTab = new javax.swing.JPanel();
        demoQuestionsTab = new javax.swing.JPanel();
        smsTab = new javax.swing.JPanel();
        messageOneLabel = new javax.swing.JLabel();
        messageOneTF = new javax.swing.JTextField();
        messageTwoLabel = new javax.swing.JLabel();
        messageTwoTF = new javax.swing.JTextField();
        messageThreeLabel = new javax.swing.JLabel();
        messageThreeTF = new javax.swing.JTextField();
        messageFourTF = new javax.swing.JTextField();
        messageFourLabel = new javax.swing.JLabel();
        messageFiveLabel = new javax.swing.JLabel();
        messageFiveTF = new javax.swing.JTextField();
        saveSMSButton = new javax.swing.JButton();
        instLabel = new javax.swing.JLabel();
        changesSavedLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        passageTextArea.setColumns(20);
        passageTextArea.setRows(5);
        jScrollPane1.setViewportView(passageTextArea);

        passageSaveButton.setText("Save Changes");

        javax.swing.GroupLayout passageTabLayout = new javax.swing.GroupLayout(passageTab);
        passageTab.setLayout(passageTabLayout);
        passageTabLayout.setHorizontalGroup(
            passageTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passageTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(passageTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passageSaveButton))
                .addContainerGap(314, Short.MAX_VALUE))
        );
        passageTabLayout.setVerticalGroup(
            passageTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passageTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passageSaveButton)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Edit Passage", passageTab);

        javax.swing.GroupLayout passageQuestionsTabLayout = new javax.swing.GroupLayout(passageQuestionsTab);
        passageQuestionsTab.setLayout(passageQuestionsTabLayout);
        passageQuestionsTabLayout.setHorizontalGroup(
            passageQuestionsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 724, Short.MAX_VALUE)
        );
        passageQuestionsTabLayout.setVerticalGroup(
            passageQuestionsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 346, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Passage Questions", passageQuestionsTab);

        javax.swing.GroupLayout demoQuestionsTabLayout = new javax.swing.GroupLayout(demoQuestionsTab);
        demoQuestionsTab.setLayout(demoQuestionsTabLayout);
        demoQuestionsTabLayout.setHorizontalGroup(
            demoQuestionsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 724, Short.MAX_VALUE)
        );
        demoQuestionsTabLayout.setVerticalGroup(
            demoQuestionsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 346, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Demographic Questions", demoQuestionsTab);

        messageOneLabel.setText("Message 1:");

        messageOneTF.setPreferredSize(new java.awt.Dimension(300, 30));

        messageTwoLabel.setText("Message 2:");

        messageTwoTF.setPreferredSize(new java.awt.Dimension(300, 30));

        messageThreeLabel.setText("Message 3:");

        messageThreeTF.setPreferredSize(new java.awt.Dimension(300, 30));

        messageFourTF.setPreferredSize(new java.awt.Dimension(300, 30));

        messageFourLabel.setText("Message 4:");

        messageFiveLabel.setText("Message 5:");

        messageFiveTF.setPreferredSize(new java.awt.Dimension(300, 30));

        saveSMSButton.setText("Save Changes");

        javax.swing.GroupLayout smsTabLayout = new javax.swing.GroupLayout(smsTab);
        smsTab.setLayout(smsTabLayout);
        smsTabLayout.setHorizontalGroup(
            smsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(smsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(smsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(messageOneLabel)
                    .addComponent(messageOneTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(messageTwoLabel)
                    .addComponent(messageTwoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(messageThreeLabel)
                    .addComponent(messageThreeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(messageFourTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(messageFourLabel)
                    .addComponent(messageFiveLabel)
                    .addComponent(messageFiveTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveSMSButton))
                .addContainerGap(414, Short.MAX_VALUE))
        );
        smsTabLayout.setVerticalGroup(
            smsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(smsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(messageOneLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(messageOneTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(messageTwoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(messageTwoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(messageThreeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(messageThreeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(messageFourLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(messageFourTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(messageFiveLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(messageFiveTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveSMSButton)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("SMS Messages", smsTab);

        instLabel.setForeground(new java.awt.Color(255, 0, 0));
        instLabel.setText("*Changes can be made by editing the text in a field and clicking 'Save Changes'. \nFields not changed will remain the same when 'Save Changes' is clicked.");

        changesSavedLabel.setForeground(new java.awt.Color(0, 180, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addComponent(instLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(changesSavedLabel)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(instLabel)
                .addGap(5, 5, 5)
                .addComponent(changesSavedLabel))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImportDataForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImportDataForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImportDataForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImportDataForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImportDataForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel changesSavedLabel;
    private javax.swing.JPanel demoQuestionsTab;
    private javax.swing.JLabel instLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel messageFiveLabel;
    private javax.swing.JTextField messageFiveTF;
    private javax.swing.JLabel messageFourLabel;
    private javax.swing.JTextField messageFourTF;
    private javax.swing.JLabel messageOneLabel;
    private javax.swing.JTextField messageOneTF;
    private javax.swing.JLabel messageThreeLabel;
    private javax.swing.JTextField messageThreeTF;
    private javax.swing.JLabel messageTwoLabel;
    private javax.swing.JTextField messageTwoTF;
    private javax.swing.JPanel passageQuestionsTab;
    private javax.swing.JButton passageSaveButton;
    private javax.swing.JPanel passageTab;
    private javax.swing.JTextArea passageTextArea;
    private javax.swing.JButton saveSMSButton;
    private javax.swing.JPanel smsTab;
    // End of variables declaration//GEN-END:variables
}
