/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjectGUI;

import java.awt.Color;
import javax.swing.BorderFactory;

/**
 *
 * @author Steve
 */
public class QuestionForm extends javax.swing.JFrame {
    public boolean gfIsMultipleChoice;

    /**
     * Creates new form QuestionForm
     */
    public QuestionForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        lblQuestion = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        btnShowTextQuestion = new javax.swing.JButton();
        rdoAnswer1 = new javax.swing.JRadioButton();
        rdoAnswer2 = new javax.swing.JRadioButton();
        rdoAnswer3 = new javax.swing.JRadioButton();
        rdoAnswer4 = new javax.swing.JRadioButton();
        rdoAnswer5 = new javax.swing.JRadioButton();
        txtAnswer = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblQuestion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblQuestion.setText("1. Which of the following is not true about personality disorders?");

        btnNext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnShowTextQuestion.setText("Text Question for Demo purposes");
        btnShowTextQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowTextQuestionActionPerformed(evt);
            }
        });

        btnGroup.add(rdoAnswer1);
        rdoAnswer1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rdoAnswer1.setText("a. They are marked by distress to the individual experiencing them");

        btnGroup.add(rdoAnswer2);
        rdoAnswer2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rdoAnswer2.setText("b. They pervade every aspect of a person's life");

        btnGroup.add(rdoAnswer3);
        rdoAnswer3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rdoAnswer3.setText("c. Affected persons respond well to psychotherapy");

        btnGroup.add(rdoAnswer4);
        rdoAnswer4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rdoAnswer4.setText("d. They tend to begin in childhood");

        btnGroup.add(rdoAnswer5);
        rdoAnswer5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rdoAnswer5.setText("Unused for this question");

        txtAnswer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnShowTextQuestion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNext))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rdoAnswer5)
                                        .addComponent(rdoAnswer4)
                                        .addComponent(rdoAnswer3))
                                    .addGap(128, 128, 128))
                                .addComponent(rdoAnswer2)
                                .addComponent(rdoAnswer1))
                            .addComponent(lblQuestion)
                            .addComponent(txtAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 35, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(lblQuestion)
                .addGap(33, 33, 33)
                .addComponent(txtAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(rdoAnswer1)
                .addGap(35, 35, 35)
                .addComponent(rdoAnswer2)
                .addGap(35, 35, 35)
                .addComponent(rdoAnswer3)
                .addGap(35, 35, 35)
                .addComponent(rdoAnswer4)
                .addGap(35, 35, 35)
                .addComponent(rdoAnswer5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNext)
                    .addComponent(btnShowTextQuestion))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            // I'm guessing maybe include all possible controls and dynamically change text, visibility, etc.
            // according to which type of question is currently required.
            txtAnswer.setVisible(false);
            rdoAnswer5.setVisible(false);
        }
        catch (Exception ex) {
            // Log exception?
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnShowTextQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowTextQuestionActionPerformed
        try {
            if (!gfIsMultipleChoice) {
                gfIsMultipleChoice = true;
                
                // Demo question
                lblQuestion.setText("2. Age (in years) - please type in a number:");
                
                rdoAnswer1.setVisible(false);
                rdoAnswer2.setVisible(false);
                rdoAnswer3.setVisible(false);
                rdoAnswer4.setVisible(false);
                rdoAnswer5.setVisible(false);
                txtAnswer.setVisible(true);
            }
            else {
                gfIsMultipleChoice = false;
                
                // Demo question
                lblQuestion.setText("1. Which of the following is not true about personality disorders?");
                
                txtAnswer.setVisible(false);
                rdoAnswer1.setVisible(true);
                rdoAnswer2.setVisible(true);
                rdoAnswer3.setVisible(true);
                rdoAnswer4.setVisible(true);
                //rdoAnswer5.setVisible(true); // in the case of our demo question there is no fifth answer.
            }
        }
        catch (Exception ex) {
            // Log exception?
        }
    }//GEN-LAST:event_btnShowTextQuestionActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        try {
            // Log results of current question to Proj Manager
            // Retrieve the next question from the DB
            // Set displayed controls, question text, radio button text, etc. based on DB info
            
            // After all questions have been answered, presumably write info to DB and close the program.
        }
        catch (Exception ex) {
            // Log exception?
        }
    }//GEN-LAST:event_btnNextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuestionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuestionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuestionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuestionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuestionForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnShowTextQuestion;
    private javax.swing.JLabel lblQuestion;
    private javax.swing.JRadioButton rdoAnswer1;
    private javax.swing.JRadioButton rdoAnswer2;
    private javax.swing.JRadioButton rdoAnswer3;
    private javax.swing.JRadioButton rdoAnswer4;
    private javax.swing.JRadioButton rdoAnswer5;
    private javax.swing.JTextField txtAnswer;
    // End of variables declaration//GEN-END:variables
}
