/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjectGUI;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.BorderFactory;
import java.util.ArrayList;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Steve
 */
public class QuestionForm extends javax.swing.JFrame {
    public boolean gfIsMultipleChoice;
    private boolean gfIsSurvey;

    /**
     * Creates new form QuestionForm
     */
    public QuestionForm() {
        initComponents();
    }
    
    public QuestionForm(boolean afIsSurvey, String asParticipantNo)
    {
        initComponents();
        
        // Are these test questions (testing user on the reading) or demographic/survey?
        gfIsSurvey = afIsSurvey;
        
        // Participant Number
        ParticipantNumber = asParticipantNo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        lblQuestion = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        rdoAnswer1 = new javax.swing.JRadioButton();
        rdoAnswer2 = new javax.swing.JRadioButton();
        rdoAnswer3 = new javax.swing.JRadioButton();
        rdoAnswer4 = new javax.swing.JRadioButton();
        rdoAnswer5 = new javax.swing.JRadioButton();
        txtAnswer = new javax.swing.JTextField();
        rdoAnswer6 = new javax.swing.JRadioButton();
        lblError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1150, 650));
        setPreferredSize(new java.awt.Dimension(1150, 650));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblQuestion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblQuestion.setText("lblQuestion");

        btnNext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnGroup.add(rdoAnswer1);
        rdoAnswer1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rdoAnswer1.setText("rdoAnswer1");

        btnGroup.add(rdoAnswer2);
        rdoAnswer2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rdoAnswer2.setText("rdoAnswer2");

        btnGroup.add(rdoAnswer3);
        rdoAnswer3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rdoAnswer3.setText("rdoAnswer3");

        btnGroup.add(rdoAnswer4);
        rdoAnswer4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rdoAnswer4.setText("rdoAnswer4");

        btnGroup.add(rdoAnswer5);
        rdoAnswer5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rdoAnswer5.setText("rdoAnswer5");

        txtAnswer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnGroup.add(rdoAnswer6);
        rdoAnswer6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rdoAnswer6.setText("rdoAnswer6");

        lblError.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblError.setForeground(new java.awt.Color(255, 0, 0));
        lblError.setText("Error Label");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(1081, Short.MAX_VALUE)
                        .addComponent(btnNext))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdoAnswer4)
                                    .addComponent(rdoAnswer3)
                                    .addComponent(rdoAnswer6)
                                    .addComponent(rdoAnswer5)
                                    .addComponent(lblError))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(rdoAnswer2)
                            .addComponent(rdoAnswer1)
                            .addComponent(txtAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(rdoAnswer1)
                .addGap(30, 30, 30)
                .addComponent(rdoAnswer2)
                .addGap(30, 30, 30)
                .addComponent(rdoAnswer3)
                .addGap(30, 30, 30)
                .addComponent(rdoAnswer4)
                .addGap(30, 30, 30)
                .addComponent(rdoAnswer5)
                .addGap(30, 30, 30)
                .addComponent(rdoAnswer6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(lblError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNext)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void addListener(QuestionFormListener toAdd)
    {
        listeners.add(toAdd);
    }
    
    public void QuestionFormCompleteEvent() {
        QuestionResultEventArgs args = new QuestionResultEventArgs(this,glResults);
        for (QuestionFormListener hl : listeners)
            hl.testQuestionFormComplete(args);
    }
    
    public void SurveyFormCompleteEvent() {
        // We may want to use a separate results class for this?
        SurveyResultEventArgs args = new SurveyResultEventArgs(this,glResults);
        for (QuestionFormListener h1: listeners)
            h1.surveyQuestionFormComplete(args);
    }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            // Clear error label
            lblError.setText("");
            
            txtAnswer.setVisible(false); // Don't show the answer textbox
            
            startTime = System.currentTimeMillis();
            
            if (!gfIsSurvey) {
                // If it's the test questions version
                this.setTitle("Questions");
                
                rdoAnswer6.setVisible(false); // No more than 5 answers per question for this form
                
                tableName = "QUESTION";
                
                try {
                    Class.forName("org.apache.derby.jdbc.ClientDriver");
                    // Get a connection
                    conn = DriverManager.getConnection(dbURL);
                }
                catch (Exception ex) {
                    ex.printStackTrace();
                }
                
                try {
                    // Select all from QUESTION table
                    stmt = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
                    questions = stmt.executeQuery("select * from " + tableName);
                    
                    // Head to the beginning so that we can call GetNextQuestion();
                    questions.beforeFirst();
                    
                    GetNextTestQuestion();
                
                    JOptionPane.showMessageDialog(null, "Please answer the following questions based on the reading you just completed. Do the best you can.", 
                            "Info", JOptionPane.INFORMATION_MESSAGE);
                }
                catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }
            else {
                // Demographic survey questions
                
                this.setTitle("Survey");
                
                tableName = "SURVEY";
                
                try {
                    Class.forName("org.apache.derby.jdbc.ClientDriver");
                    // Get a connection
                    conn = DriverManager.getConnection(dbURL);
                }
                catch (Exception ex) {
                    ex.printStackTrace();
                }
                
                try {
                    // Select all from QUESTION table
                    stmt = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
                    questions = stmt.executeQuery("select * from " + tableName);
                    
                    // Head to the beginning so that we can call GetNextQuestion();
                    questions.beforeFirst();
                    
                    GetNextSurveyQuestion();
                    
                    
                    JOptionPane.showMessageDialog(null, "For all of the items in this section, please report how each statement describes your behavior, feelings or ideas." 
                        + "\n\nPlease indicate your agreement with each of the statements using the scale provided. Please press ''next'' to advance to the next question.", 
                        "Info", JOptionPane.INFORMATION_MESSAGE);
                }
                catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }
        }
        catch (Exception ex) {
            // Log exception?
        }
    }//GEN-LAST:event_formWindowOpened

    private boolean isEmpty(String input)
    {
        // Method allowing me to more easily check whether questions are empty, since there can be 0-6 questions
        return input.compareTo("") == 0;
    }
    
    private void AddResults() throws SQLException {
        if (!gfIsSurvey) {
            // Handle test results
            
            long llCurrentTime = System.currentTimeMillis(); // Take current time
            double ldQuestionTime = (llCurrentTime - startTime) / 1000.0; // Subtract to get elapsed time
            
            // Determine selected answer
            String lsAnswer = "";
        
            if (rdoAnswer1.isSelected()) {
                lsAnswer = "A";
            }
            else if (rdoAnswer2.isSelected()) {
                lsAnswer = "B";
            }   
            else if (rdoAnswer3.isSelected()) {
                lsAnswer = "C";
            }
            else if (rdoAnswer4.isSelected()) {
                lsAnswer = "D";
            }
            else if (rdoAnswer5.isSelected()) {
                lsAnswer = "E";
            }
            
            // Check for correctness
            boolean lfIsCorrect = (lsAnswer.compareTo(gsCurrentCorrectAnswer) == 0);
            
            // Currently an Object[] with an ArrayList to hold them, but that is subject to change, as are the contents.
            Object[] loQuestionResult = new Object[5];
            
            loQuestionResult[0] = ParticipantNumber; // Participant Number should be included with all results
            loQuestionResult[1] = questions.getInt(1); // Get the question ID
            loQuestionResult[2] = lsAnswer; // User's answer - ask Dr. Bowman, do we need this or do we just care if it's correct?
            loQuestionResult[3] = lfIsCorrect; // Is the user's answer correct?
            loQuestionResult[4] = ldQuestionTime; // Elapsed time
            
            glResults.add(loQuestionResult); // Add the object[] to the arraylist
        }
        else {
            // Handle survey results
            String lsMultipleChoiceAnswer = null;
            String lsOpenEndedAnswer = null;
            
            if (rdoAnswer1.isSelected()) {
                lsMultipleChoiceAnswer = "A";
            }
            else if (rdoAnswer2.isSelected()) {
                lsMultipleChoiceAnswer = "B";
            }   
            else if (rdoAnswer3.isSelected()) {
                lsMultipleChoiceAnswer = "C";
            }
            else if (rdoAnswer4.isSelected()) {
                lsMultipleChoiceAnswer = "D";
            }
            else if (rdoAnswer5.isSelected()){
                lsMultipleChoiceAnswer = "E";
            }
            else if (rdoAnswer6.isSelected()) {
                lsMultipleChoiceAnswer = "F";
            }
            
            if (txtAnswer.getText().compareTo("") != 0) {
                lsOpenEndedAnswer = txtAnswer.getText();
                txtAnswer.setText("");
            }
            
            Object[] loQuestionResult = new Object[4];
            
            loQuestionResult[0] = ParticipantNumber; // Participant Number should be included with all results
            loQuestionResult[1] = questions.getInt(1); // Get the question ID
            loQuestionResult[2] = lsOpenEndedAnswer; // Open-ended answer
            loQuestionResult[3] = lsMultipleChoiceAnswer; // Multiple choice answer
            
            glResults.add(loQuestionResult);
        }
    }
    
    private void GetNextTestQuestion() throws SQLException {
        // Deselect the questions
        btnGroup.clearSelection();
        
        // Advance within the result set
        questions.next();
        
        // Get the question, answers and correct answer from the result set
        String lsQuestion = questions.getString(2);
        String lsAnswerA = questions.getString(3);
        String lsAnswerB = questions.getString(4);
        String lsAnswerC = questions.getString(5);
        String lsAnswerD = questions.getString(6);
        String lsAnswerE = questions.getString(7);
        gsCurrentCorrectAnswer = questions.getString(8);
                    
        // Set the question label text - the html tags are somewhat of a hack used to get text wrap in the label
        lblQuestion.setText("<html>" + lsQuestion + "</html>");
        
        // If the answers are not empty, set their text and set them visible. Else, set them invisible.
        if (!isEmpty(lsAnswerA.trim())) {
            rdoAnswer1.setText(lsAnswerA);
            rdoAnswer1.setVisible(true);
        }
        else {
            rdoAnswer1.setVisible(false);
        }

        if (!isEmpty(lsAnswerB.trim())) {
            rdoAnswer2.setText(lsAnswerB);
            rdoAnswer2.setVisible(true);
        }
        else {
            rdoAnswer2.setVisible(false);
        }

        if (!isEmpty(lsAnswerC.trim())) {
            rdoAnswer3.setText(lsAnswerC);
            rdoAnswer3.setVisible(true);
        }
        else {
            rdoAnswer3.setVisible(false);
        }

        if (!isEmpty(lsAnswerD.trim())) {
            rdoAnswer4.setText(lsAnswerD);
            rdoAnswer4.setVisible(true);
        }
        else {
            rdoAnswer4.setVisible(false);
        }

        if (!isEmpty(lsAnswerE.trim())) {
            rdoAnswer5.setText(lsAnswerE);
            rdoAnswer5.setVisible(true);
        }
        else {
            rdoAnswer5.setVisible(false);
        }
    }
    
    private void GetNextSurveyQuestion() throws SQLException {
        // Deselect the questions
        btnGroup.clearSelection();
        
        // Advance within the result set
        questions.next();
        
        // Display the appropriate prompt before the start of the demographic questions
        if (questions.getInt(1) == 6)
            JOptionPane.showMessageDialog(null, "Please complete the response to each question that best describes you.", 
            "Info", JOptionPane.PLAIN_MESSAGE);
        
        // Get the question, answers and correct answer from the result set - the html tags are somewhat of a hack used to get text wrap in the label
        String lsQuestion = questions.getString(2);
        String lsAnswerA = questions.getString(3);
        String lsAnswerB = questions.getString(4);
        String lsAnswerC = questions.getString(5);
        String lsAnswerD = questions.getString(6);
        String lsAnswerE = questions.getString(7);
        String lsAnswerF = questions.getString(8);
                    
        // Set the question label text
        lblQuestion.setText("<html>" + lsQuestion + "</html>");
        
        if (questions.getBoolean(9))
            txtAnswer.setVisible(true);
        else
            txtAnswer.setVisible(false);
        
        // If the answers are not empty, set their text and set them visible. Else, set them invisible.
        if (!isEmpty(lsAnswerA.trim())) {
            rdoAnswer1.setText(lsAnswerA);
            rdoAnswer1.setVisible(true);
        }
        else {
            rdoAnswer1.setVisible(false);
        }

        if (!isEmpty(lsAnswerB.trim())) {
            rdoAnswer2.setText(lsAnswerB);
            rdoAnswer2.setVisible(true);
        }
        else {
            rdoAnswer2.setVisible(false);
        }

        if (!isEmpty(lsAnswerC.trim())) {
            rdoAnswer3.setText(lsAnswerC);
            rdoAnswer3.setVisible(true);
        }
        else {
            rdoAnswer3.setVisible(false);
        }

        if (!isEmpty(lsAnswerD.trim())) {
            rdoAnswer4.setText(lsAnswerD);
            rdoAnswer4.setVisible(true);
        }
        else {
            rdoAnswer4.setVisible(false);
        }

        if (!isEmpty(lsAnswerE.trim())) {
            rdoAnswer5.setText(lsAnswerE);
            rdoAnswer5.setVisible(true);
        }
        else {
            rdoAnswer5.setVisible(false);
        }
        
        if (!isEmpty(lsAnswerF.trim())) {
            rdoAnswer6.setText(lsAnswerF);
            rdoAnswer6.setVisible(true);
        }
        else {
            rdoAnswer6.setVisible(false);
        }
    }
    
    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        try {
            lblError.setText("");
            if (!gfIsSurvey) {
                // Ensure that an answer is selected.
                if (rdoAnswer1.isSelected() || rdoAnswer2.isSelected() || rdoAnswer3.isSelected() || rdoAnswer4.isSelected() || rdoAnswer5.isSelected()) {
                    AddResults();

                    if (!questions.isLast()) 
                        GetNextTestQuestion();
                    else
                        QuestionFormCompleteEvent();
                }
                else {
                    lblError.setText("Please select an answer.");
                }
            }
            else {
                // Check for any radio button being selected
                if ((rdoAnswer1.isSelected() || rdoAnswer2.isSelected() || rdoAnswer3.isSelected() || rdoAnswer4.isSelected() || rdoAnswer5.isSelected() || rdoAnswer6.isSelected())
                        // or an open-ended question with a non-blank response
                        || (questions.getBoolean(9) && txtAnswer.getText().compareTo("") != 0)) {
                    AddResults();

                    if (!questions.isLast()) 
                        GetNextSurveyQuestion();
                    else {
                        JOptionPane.showMessageDialog(null, "This concludes the experiment." 
                            + "\n\nThank you so much for participating!", 
                            "Info", JOptionPane.PLAIN_MESSAGE);
                        SurveyFormCompleteEvent();
                    }
                }
                else {
                    lblError.setText("Please provide an answer.");
                }
            }
        }
        catch (Exception ex) {
            // Log exception?
        }
    }//GEN-LAST:event_btnNextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuestionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuestionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuestionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuestionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuestionForm().setVisible(true);
            }
        });
    }
    
    // Global variables
    private final ArrayList<QuestionFormListener> listeners = new ArrayList();
    private String ParticipantNumber; 
    private long startTime;
    private ResultSet questions;
    private String gsCurrentCorrectAnswer;
    private ArrayList<Object[]> glResults = new ArrayList();
    
    // For DB
    private static String dbURL = "jdbc:derby://localhost:1527/sidresDB;create=true;user=sidresAdmin;password=1x!Software";
    private static String tableName;
    // jdbc Connection
    private static Connection conn = null;
    private static Statement stmt = null;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JButton btnNext;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblQuestion;
    private javax.swing.JRadioButton rdoAnswer1;
    private javax.swing.JRadioButton rdoAnswer2;
    private javax.swing.JRadioButton rdoAnswer3;
    private javax.swing.JRadioButton rdoAnswer4;
    private javax.swing.JRadioButton rdoAnswer5;
    private javax.swing.JRadioButton rdoAnswer6;
    private javax.swing.JTextField txtAnswer;
    // End of variables declaration//GEN-END:variables
}
